//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kayitentity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Hocalar1
    {
        public int id { get; set; }
        public string Hoca { get; set; }
        public Nullable<int> idHoca { get; set; }
    
        public virtual Ders_Adlari Ders_Adlari { get; set; }
    }
}
