//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kayitentity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class KayıtSistemiEntities : DbContext
    {
        public KayıtSistemiEntities()
            : base("name=KayıtSistemiEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Ders_Adlari> Ders_Adlari { get; set; }
        public virtual DbSet<Ders_Secim> Ders_Secim { get; set; }
        public virtual DbSet<Hocalar1> Hocalar1 { get; set; }
        public virtual DbSet<Secilen_Dersler> Secilen_Dersler { get; set; }
        public virtual DbSet<son> son { get; set; }
    }
}
