//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kayitentity
{
    using System;
    using System.Collections.Generic;
    
    public partial class son
    {
        public int id { get; set; }
        public string DersKodu { get; set; }
        public string Kredi { get; set; }
        public string Saat { get; set; }
        public string DersAdi { get; set; }
        public string Hoca { get; set; }
    }
}
